stages:
  - fs: "shaders/scene2d.glsl"
    target: "scene2d"
    wrap_mode: repeat
    float: true

  - fs: "shaders/scene3d.glsl"
    target: "scene3d"
    wrap_mode: repeat
    float: true

  - fs: "shaders/transcendental_cube.glsl"
    # resolution: [640, 360]
    # resolution: [1280, 720]
    resolution: [854, 480]
    target: "transcendental_cube"
    wrap_mode: repeat

  - fs: "shaders/composite.glsl"
    target: "composite"
    wrap_mode: repeat
    float: true

  - fs: "shaders/post_bloom_blur.glsl"
    resolution: [640, 360]
    target: "post_bloom_blur"
    wrap_mode: repeat
    float: true

  - fs: "shaders/post_bloom_composite.glsl"
    target: "post_bloom_composite"
    wrap_mode: repeat
    float: true

  - fs: "shaders/post_final.glsl"

images:
  - path: "images/font_receipt_all.png"
    name: "font_receipt_all"
  - path: "images/font_orbitron_ascii.png"
    name: "font_orbitron_ascii"
  - path: "images/draw_logo.png"
    name: "draw_logo"
  - path: "images/draw_logo_tokyo.png"
    name: "draw_logo_tokyo"
  - path: "images/gam0022.png"
    name: "gam0022"
  - path: "images/toufu0301.png"
    name: "toufu0301"
  - path: "images/toufu0301_full.jpg"
    name: "toufu0301_full"

midi_devices:
  - "loopMIDI"
  - "nanoKONTROL2"

audio:
  audio_samples: 8192
  spectrum:
    mipmap: true
    filter: linear
    wrap_mode: repeat
