stages:
  - fs: "shaders/scene2d.glsl"
    target: "scene2d"
    wrap_mode: repeat

  - fs: "shaders/scene3d.glsl"
    target: "scene3d"
    wrap_mode: repeat

  - fs: "shaders/transcendental_cube.glsl"
    # resolution: [640, 360]
    # resolution: [1280, 720]
    resolution: [854, 480]
    target: "transcendental_cube"
    wrap_mode: repeat

  - fs: "shaders/composite.glsl"
    target: "composite"
    wrap_mode: repeat

  - fs: "shaders/posteffect.glsl"

images:
  - path: "images/font_receipt_all.png"
    name: "font_receipt_all"
  - path: "images/font_orbitron_ascii.png"
    name: "font_orbitron_ascii"

midi_devices:
  - "loopMIDI"
  - "nanoKONTROL2"

audio:
  audio_samples: 8192
  spectrum:
    mipmap: true
    filter: linear
    wrap_mode: repeat
